### ISSUE TITLE
Readme example fails with keeyerror

### ISSUE THREAD

**Issue by shimwell** [IAEA-NDS/exfor_json#1]
Hi IAEA

Thanks for making the repo.

I'm just taking a look and noticed the example in the readme doesn't work straight away.

I'm getting this error

```
Traceback (most recent call last):
  File "/home/j/exfor_json/plot.py", line 8, in <module>
    entry_data = data["003"]["data"]
                 ~~~~^^^^^^^
KeyError: '003'
```

Wondering if this is an easy fix for someone who knows the data structure better than me

slightly related [package](https://github.com/nschloe/pytest-codeblocks) that might be handy

**Comment by shinokumura** [comment]
@shimwell The README has been corrected in this [commit](https://github.com/IAEA-NDS/exfor_json/commit/a983c1056790378bb3eb22effad248ddc969ad03). It previously referred to an old version. and will try [pytest](https://github.com/nschloe/pytest-codeblocks), thanks for the suggestion!

**Comment by shimwell** [comment]
Thanks for solving that issue
