### ISSUE TITLE
request for license

### ISSUE THREAD

**Issue by shimwell** [IAEA-NDS/exfor_json#2]
many thanks for making the repository.

would it be possible to add a license file.

this will help me check if I'm able to make use of the package in the way I hope to

thanks

**Comment by julia-sprenger** [comment]
Hi @shimwell,
thanks for raising the issue, it's a very good point.

@shinokumura I added the CC-BY license according to the IAEA NDS policy, see #3.

**Comment by shinokumura** [comment]
Hi @shimwell, @julia-sprenger, License added accordingly. Thank you for your request!

**Comment by shimwell** [comment]
thanks for solving this issue, I shall close it but feel free to reopen if anyone wants
